name: Pull Request
on: [pull_request]
jobs:
  PulRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "students_tests"
          envkey_DATABASE_URL: "postgresql://postgres:postgres@students_ci_cd_db:5432/students_tests"
          file_name: ".env.test"
      - name: Run tests
        run: docker-compose -f docker-compose-tests.yml run students_ci_cd npm run test